[package]
name = "ledwall-designer"
version = "1.0.1"
description = "Offline LED wall design and technical documentation"
license = "GPL-3.0-only"
repository = "https://github.com/LorenzoApra/Ledwall-Designer"
authors = ["ATS"]
edition = "2021"

[lib]
name = "ledwall_designer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
